version: '3.7'

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wp
      o: bind

services:

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress_image
    container_name: wordpress_container
    volumes:
      - wp:/var/www/html/
    ports:
      - "9000:9000"
    env_file: .env
    restart: always
    depends_on:
      - mariadb
    networks:
      - mynetwork

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb_image
    container_name: mariadb_container
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - mynetwork

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx_image
    container_name: nginx_container
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - mynetwork
    volumes:
      - wp:/var/www/html

networks:
  mynetwork:
